// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc8kuv0y7WRsBEr9-4AR0uGKOiP0EU3bM',
    appId: '1:402934252361:web:b599b5326d40e87d189098',
    messagingSenderId: '402934252361',
    projectId: 'city-guide-ff678',
    authDomain: 'city-guide-ff678.firebaseapp.com',
    storageBucket: 'city-guide-ff678.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAziGnsXauaQ7a5adc6YyUlgDcvV-ntzw',
    appId: '1:402934252361:android:c9384f1af72dd8d8189098',
    messagingSenderId: '402934252361',
    projectId: 'city-guide-ff678',
    storageBucket: 'city-guide-ff678.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx3IuJVeN1p0aKLD8_9QtC71FnAd47sHg',
    appId: '1:402934252361:ios:0f6e1eaee30a9603189098',
    messagingSenderId: '402934252361',
    projectId: 'city-guide-ff678',
    storageBucket: 'city-guide-ff678.firebasestorage.app',
    iosBundleId: 'com.example.cityGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx3IuJVeN1p0aKLD8_9QtC71FnAd47sHg',
    appId: '1:402934252361:ios:0f6e1eaee30a9603189098',
    messagingSenderId: '402934252361',
    projectId: 'city-guide-ff678',
    storageBucket: 'city-guide-ff678.firebasestorage.app',
    iosBundleId: 'com.example.cityGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc8kuv0y7WRsBEr9-4AR0uGKOiP0EU3bM',
    appId: '1:402934252361:web:9297145fb35aa83b189098',
    messagingSenderId: '402934252361',
    projectId: 'city-guide-ff678',
    authDomain: 'city-guide-ff678.firebaseapp.com',
    storageBucket: 'city-guide-ff678.firebasestorage.app',
  );

}